[package]
name = "zufall"
description = "Zufall, a tool to help on decisions."
version = "3.2.0-rolling"
license = "MIT"
edition = "2021"

[dependencies]
rand = "0.8"
gtk = { version = "0.16.0", features = ["v3_24"] }
