[package]
name = "zufall"
description = "Zufall, a tool to help on decisions."
version = "3.2.0-rolling"
authors = ["rusty-snake"]
license = "MIT"
edition = "2021"

[dependencies]
rand = "0.8"
clap = { version = "2", features = ["wrap_help"] }
gtk = { version = "0.15.0", features = ["v3_24"] }
